<pre class='metadata'>
Title: TrinPod Documentation
Shortname: trinpod-docs
Level: 1
Status: DRAFT
Group: Graphmetrix
URL: Your spec url
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract: A short description of your spec, one or two sentences.
</pre>

Introduction {#intro}
=====================

Introduction here.
